Rails/MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    get :activate, on: :collection
  end


  resource :sessions, only: [:new, :create, :destroy]

  resources :bands

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy]

  resources :albums do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]

  resources :notes, only: [:new, :create, :destroy]
end

Rails/MusicApp/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :band_id, presence: true
  validates :studio, inclusion: { in: [true, false] }
  validates :year, numericality: { greater_than: 1900, less_than: 2030, allow_nil: true}

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

Rails/MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_logged_in!, except: :show
  
  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def new    
    @bands = Band.all
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_band_album_url(@album.band_id)
    end
  end

  def edit
    @bands = Band.all
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def update
    @album = Album.find_by(id: params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to edit_album_url(@album)
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private 
  def album_params
    params.require(:albums).permit(:title, :year, :studio, :band_id)
  end
end

Rails/MusicApp/app/views/albums/_albumform.html.erb
<% action_url = (action == "add") ? albums_url : album_url(album.id) %>
<% button = (action == "add") ? "Add" : "Update" %>

<%= render "shared/errors" %>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>

  <% if action == "edit" %>
  <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="band">Band/Artist</label>  
  <select id="band" name="albums[band_id]">  
  <% unless @bands.nil? %>
    <% @bands.each do |band| %>
      <option value="<%= band.id %>" <%= band.id == album.band_id ? "selected" : "" %>><%= band.name %></option>
    <% end %>
  </select>
  <% end %>
  <br>
  <label for="title">Title</label>
  <input type="text" id="title" name="albums[title]" value="<%= album.title %>">
  <br>
  <label for="year">Year</label>
  <input type="number" id="year" name="albums[year]" value="<%= album.year %>">
  <br>
  <p>Is this a studio album or live album?</p>
  <label for="studio">Studio</label>
  <input type="radio" id="studio" name="albums[studio]" value="t" <%= album.studio ? "checked" : "" %>>
  <label for="live">Live</label>
  <input type="radio" id="live" name="albums[studio]" value="f" <%= album.studio ? "" : "checked" %>>
  <br>
  <input type="submit" value="<%= button %>">
</form>

<% if action == "edit" %>
  <%= button_to "Delete Album", album_url(album.id), method: :delete %>
<% end %>

Rails/MusicApp/app/views/albums/edit.html.erb
<h1>Update Album Info</h1>

<%= render "albumform", album: @album, action: "edit" %>

Rails/MusicApp/app/views/albums/new.html.erb
<h1>Add an album</h1>

<%= render "albumform", action: "add", album: @album %>

Rails/MusicApp/app/views/albums/show.html.erb
<table>
  <thead>
    <tr>
      <th colspan="2"><%= @album.title %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Band</td>
      <td><%= @album.band.name %></td>
    </tr>
    <tr>
      <td>Year</td>
      <td><%= @album.year %></td>      
    </tr>
    <tr>
      <td>Live/Studio</td>
      <td><%= @album.studio ? "Studio" : "Live" %></td>
    </tr>
  </tbody>
</table>



<% if @album.tracks.empty? %>
  <p>No tracks... yet!</p>
<% else %>
  <p>Tracks</p>
  <ul>
    <% @album.tracks.each do |track|%>
      <li><%= link_to "#{track.title}", track_url(track) %></li>
    <% end %>
  </ul>
<% end %>

<br>
<%= link_to "Edit", edit_album_url %>
<br>
<%= link_to "Add track", new_album_track_url(@album) %>
<br>
<%= link_to "Back to artist", band_url(@album.band_id) %>